GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJOdXJoYW5pZiBTaGlkZGlxIEFndXN0aWFuIiwiZW1haWwiOiJudXJhc2hpZGFuMDRAZ21haWwuY29tIiwiaWF0IjoxNzE4MjQyMTAzLCJleHAiOjE3MTgyNDIxMzN9.uXxT5VqB4LufXQUMOIX4OVIU5ApODPI0m54C9OlNPng
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nurhanif Shiddiq Agustian",
    "email": "nurashidan04@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "nurashidan04@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
